#  (_____)                                         (_____)
#  |   |~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|   |
#  |   | ##     ## ##    ## ########  ####  ######  |   |
#  |   |  ##   ##   ##  ##  ##     ##  ##  ##    ## |   |
#  |   |   ## ##     ####   ##     ##  ##  ##       |   |
#  |   |    ###       ##    ########   ##   ######  |   |
#  |   |   ## ##      ##    ##   ##    ##        ## |   |
#  |   |  ##   ##     ##    ##    ##   ##  ##    ## |   |
#  |   | ##     ##    ##    ##     ## ####  ######  |   |
#  |   |    Xyris Death Messages - XyrisPlugins     |   |
#  |___|~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|___|
#  (_____)         https://xyris.fun/devs          (_____)

# Welcome to the configuration file for Xyris Death Messages. It's very easy to edit all the settings. If you encounter any issues while configuring or discover any bugs, please feel free to contact us at xyris.fun/devs.


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Titles
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# Placeholders:
# %attacker% - Returns the attacker name.
# %victim% - Returns the victim name.

kill-titles:
  enabled: true
  kill-title: '&#00FF07&lʏᴏᴜ ᴡᴏɴ!'
  kill-subtitle: '&7You defeated %victim%!'

death-titles:
  enabled: true
  death-title: '&#FF0000&lʏᴏᴜ ʟᴏsᴛ!'
  death-subtitle: '&7You have been slain by %attacker%!'

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Action Bars
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# Placeholders:
# %attacker% - Returns the attacker name.
# %victim% - Returns the victim name.
# %attacker_health% - Returns the attacker health.
# %victim_health% - Returns the victim health.

kill-action-bar:
  enabled: true
  message: '&7You defeated &#00FF07%victim% &7with &#00FF07❤ %attacker_health%&7!'

death-action-bar:
  enabled: true
  message: '&7You were defeated by &#FF0000%attacker% &7with &#FF0000❤ %attacker_health%&7!'

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Death Messages
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# Placeholders:
# %attacker% - Returns the attacker name.
# %victim% - Returns the victim name.
# %attacker_health% - Returns the attacker health.

death_messages:
  custom:
    - '&#FF0000%victim%&7 has been killed by &#FF0000%attacker% &8(&7❤ %attacker_health%&8)'
    - '&#00FFFF%victim%&7 has been killed by &#00FFFF%attacker% &8(&7❤ %attacker_health%&8)'

# You can add more death messages here!
# Done configuring the plugin? Execute the command '/xyrisdm reload' in-game to apply the changes.