name: XyrisDeathMessages
version: '2.0'
main: xyris.darkxx.xyrisdm.Main
api-version: '1.19'
author: Darkxx
website: darkxx.xyz
commands:
  xyrisdm:
    permission: xyrisdm.reload
  toggldeathmessages: